apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-demo-install
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: in-cluster
  source:
    path: cluster-lab/in-cluster/kafka-demo-install
    repoURL: https://github.com/danielbraga/openshift-gitops-sandbox
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false