kind: Kafka
apiVersion: kafka.strimzi.io/v1beta2
metadata:
  name: my-cluster-qua
  namespace: kafka-qua-cust
spec:
  kafka:
    authorization:
      type: simple
    config:
      allow.everyone.if.no.acl.found: true
      authorizer.class.name: kafka.security.authorizer.AclAuthorizer
      auto.create.topics.enable: true
      default.replication.factor: 3
      inter.broker.protocol.version: '3.8'
      log.retention.hours: 3
      min.insync.replicas: 2
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    listeners:
      - name: plain
        port: 9092
        tls: false
        type: internal
      - authentication:
          type: scram-sha-512
        name: http
        port: 9095
        tls: true
        type: route
      - authentication:
          type: scram-sha-512
        name: authint
        port: 9094
        tls: false
        type: internal
      - authentication:
          type: scram-sha-512
        configuration:
          bootstrap:
            nodePort: 32064
        name: tls
        port: 9093
        tls: true
        type: nodeport
    replicas: 3
    storage:
      type: ephemeral
    version: 3.8.0
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: { }
    userOperator: { }