apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-namespaces-app
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cluster-lab/namespaces/resources
    repoURL: https://github.com/danielbraga/openshift-gitops-sandbox
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false